#!/bin/bash -e
#
# Tool to list all symbols that are defined in more than one source file.
#
#   $ ./tools/lsmacros src/*.c
#

# ls-macros lists all defined macros of the given files.
# Output is one line per (file, symbol) pair.
ls-macros() {
    for f in "$@"; do
        sed -r -e 's:\s*#\s*define\s+([^( \t]+)[( \t].*:\1: p ; d' "$f" | sort -u | awk -vf="$f" '{ print f, $1; }'
    done
}

# group-files takes lines of (file, symbol) and outputs (symbol, file*).
group-files() {
    sort -k2,2 -k1,1 | awk '
        $2 != sym && sym { printf "%s%s\n", sym, fnames; fnames = ""; }
        { sym = $2; fnames = fnames " " $1; }
        END { if (sym) printf "%s%s\n", sym, fnames; }'
}

# Output all symbols defined in more than one file.
ls-macros "$@" | group-files | awk 'NF > 2 { print; }'
